Added Swedish translation
runely/calendar-homey pull request #270
Opened 2022-01-06 11:12 UTC by Lavve

2022-01-06 17:35 UTC, runely commented on README.sv.txt
> +    Klistra in ical-länken
Legg til en '-' :)

2022-01-06 17:35 UTC, runely commented on README.sv.txt
> +Klicka på Inställningar -> Visa alla Outlook-inställningar
Legg til '2. '

2022-01-06 17:36 UTC, runely commented on README.sv.txt
> +Klistra in ical-länken i inställningarna i Homey-appen
Legg til '5. '

2022-01-06 17:36 UTC, runely commented on README.sv.txt
> +Klicka på de tre prickarna bredvid kalendern du vill använda -> Klicka på Inställningar och delning
Legg til '2. '

2022-01-06 17:36 UTC, runely commented on README.sv.txt
> +Skrolla hela vägen till botten
Legg til '3. '

2022-01-06 17:36 UTC, runely commented on README.sv.txt
> +Klistra in ical-länken i inställningarna i Homey-appen
Legg til '5. '

2022-01-06 17:37 UTC, runely commented on README.sv.txt
> +Klistra in länken i inställningarna i Homey-appen
Legg til '5. '

2022-01-06 17:39 UTC, runely commented on README.sv.txt
> +Händelser hämtas automatiskt var 15:e minut
Legg til '- '

2022-01-06 17:39 UTC, runely commented on README.sv.txt
> +Endast händelser som inte har påbörjats ännu, eller möten som har påbörjats men inte avslutats och som har ett startdatum inom 2 månader eller mindre kommer att hämtas (kan ändras i inställningarna)
Legg til '- '

2022-01-06 17:48 UTC, runely requested changes
Thank your for adding Swedish.

However i found some things to fix in `README.sv.txt`.

Also, `app.json` is autogenerated from files in `.homeycompose` folder, so all swedish translations and other changes must be moved to the correct files in `.homeycompose/...` before i'll merge this in

2022-01-07 10:12 UTC, Lavve commented
Some kind of heads up in the README or similar would have been much appreciated. ;)

2022-01-07 19:31 UTC, runely requested changes
Awesome, just one small typo left 👍

2022-01-07 19:31 UTC, runely commented on .homeycompose/flow/conditions/any_event_in.json
> +      "sv": "En händelse !{{snartar|startar inte}} inom..."
startar ;)

2022-01-08 09:39 UTC, runely approved these changes
All good 👍

2022-01-08 09:45 UTC, runely commented
Is it okey if i put your name `Magnus Claesson` as a translator? It will show up in the bottom of the apps page under `Contributors`.

I will also put your github username on the README page here on GitHub, if thats okey

2022-01-08 09:49 UTC, runely commented
I see you have added it yourself, so i'm guessing it's okey 😛

2022-01-08 09:49 UTC, merged

2022-01-08 14:24 UTC, runely commented
v0.10.0 is published and are `In review` at Athom